export const videoInsightEvents = {
  insightAdded: 'video-insights:insight-added',
  cancelEdit: 'video-insights:cancel-edit',
  edit: 'video-insights:edit',
  endHighlightAnimation: 'video-insights:end-highlight-animation',
  highlightByResponseId: 'video-insights:highlight-by-response-id',
  delete: 'video-insights:remove',
  deleted: 'video-insights:removed',
  save: 'video-insights:save',
  saved: 'video-insights:saved',
  scrollTo: 'video-insights:scroll-to',
  // scrollToResponse: 'video-insights:scroll-to-response',
  scrollToTop: 'video-insights:scroll-to-top',
  tryAdd: 'video-insights:try-add',
  tryRemove: 'video-insights:try-remove',
  tryEdit: 'video-insights:try-edit',
  update: 'video-insights:update',
  updated: 'video-insights:updated',
};
